### ISSUE TITLE
Dropping qt5 use flag in qtchooser

### ISSUE THREAD

**Issue by alexjp** [mmstick/bomi-overlay#1]
Hi,

Latest version of qtchooser no longer has the qt5 flag.
Could this be dropped in the ebuild? dev-qt/qtchooser[qt5] for dev-qt/qtchooser only ?

Thanks for the ebuild.

**Comment by mmstick** [comment]
Done (a70ca1bd77b0a770a15c9d43ffc6c0e40c4a1055)
